title: generic-python-turtle-moving
hero_image: images/banner.png
description: generic-python-turtle-moving description
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: cc-prototype
duration: 1 # 1, 2 or 3
listed: false
ingredient: false
interests: "games"
technologies: "python, scratch"
steps:
  - title: Step one
